/**:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.1
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link_1
    world_frame: odom

    imu0: /drone1/imu_sanitized
    # 2D mode: use yaw + yaw rate (ignore roll/pitch and linear accel).
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: false

    twist0: /drone1/flight_twist_cov
    # 2D mode: use planar linear velocities only.
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  true,  false,
                    false, false, false,
                    false, false, false]
    twist0_differential: false
    twist0_relative: false

    # ekf_flightdata.yaml に追記
    odom0: /drone1/rgbd_odom # rgbd_odometryが出力するトピック
    odom0_config: [true,  true, false,   # x, yを使用
                  false, false, true,   # yaw を使用（pitch, rollはIMU等に任せる）
                  false, false, false, 
                  false, false, false,
                  true, true, false]
    odom0_relative: false    # 【修正】絶対位置を使用
    odom0_differential: true # 【修正】速度として差分を使用
