/**:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.1
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link_1
    world_frame: odom

    twist0: flight_twist_cov
    # 2D mode: use planar linear velocities only.
    twist0_config: [false, false, false,
                    false, false, false,
                    true,  true,  false,
                    false, false, false,
                    false, false, false]
    twist0_differential: false
    twist0_relative: false
